tenant:
  hostname: "dpoplayconfig.int-aws-de.webmethods.io"   # webMthodsIO Integration hostname or ip address
  port: "443"                                       # webMthodsIO Integration port
  admin_username: "srini"                     # webMthodsIO Integration user  
  type: "prod"                                         #PROD